// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCixF5At2Zq1JYvlAw5wk1qso3tBnPXIkg',
    appId: '1:1047025780446:web:97c2007c5f284adc17644f',
    messagingSenderId: '1047025780446',
    projectId: 'greenquest-af32c',
    authDomain: 'greenquest-af32c.firebaseapp.com',
    storageBucket: 'greenquest-af32c.appspot.com',
    measurementId: 'G-L3MWZG7N4C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATZu5okAsMi-ytZICsfwdV1hsuaC-6Uwc',
    appId: '1:1047025780446:android:8dc6aec50023f34617644f',
    messagingSenderId: '1047025780446',
    projectId: 'greenquest-af32c',
    storageBucket: 'greenquest-af32c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhk3NUPxBRGV9HDFfTJsqKqmjPrxx1ONs',
    appId: '1:1047025780446:ios:a3d4d348af88d59517644f',
    messagingSenderId: '1047025780446',
    projectId: 'greenquest-af32c',
    storageBucket: 'greenquest-af32c.appspot.com',
    iosBundleId: 'com.example.greenQuest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhk3NUPxBRGV9HDFfTJsqKqmjPrxx1ONs',
    appId: '1:1047025780446:ios:a3d4d348af88d59517644f',
    messagingSenderId: '1047025780446',
    projectId: 'greenquest-af32c',
    storageBucket: 'greenquest-af32c.appspot.com',
    iosBundleId: 'com.example.greenQuest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCixF5At2Zq1JYvlAw5wk1qso3tBnPXIkg',
    appId: '1:1047025780446:web:5f5e9649f24f644617644f',
    messagingSenderId: '1047025780446',
    projectId: 'greenquest-af32c',
    authDomain: 'greenquest-af32c.firebaseapp.com',
    storageBucket: 'greenquest-af32c.appspot.com',
    measurementId: 'G-VYTMQYK1H7',
  );
}
